version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: wiseprompt-db-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wiseprompt
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - wiseprompt-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Nest.js) - Development mode with hot reload
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: wiseprompt-api-dev
    restart: always
    ports:
      - "3001:3001"
      - "9229:9229" # For debugging
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/wiseprompt?schema=public
      JWT_SECRET: your-secret-key-for-development
      JWT_EXPIRATION: 7d
      NODE_ENV: development
      PORT: 3001
      DOMAIN: localhost
      ORIGIN: http://localhost:3000
    networks:
      - wiseprompt-network-dev
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run start:dev

  # Frontend (Next.js) - Development mode with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wiseprompt-frontend-dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    networks:
      - wiseprompt-network-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

networks:
  wiseprompt-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local
